### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dxvine** [divine/reserved-usernames#2]

**Comment by szepeviktor** [comment]
https://github.com/divine/reserved-usernames/blob/534754cce37a1a7c10bb3c7e775a10efc1fe392e/src/ReservedUsernames.php#L3

https://github.com/divine

**Comment by dxvine** [comment]
I didn't understand what you want to say bruh

**Comment by szepeviktor** [comment]
> I didn't understand what you want to say bruh

That you are not talking about this repo but about a GitHub account https://github.com/divine

**Comment by dxvine** [comment]
Yes ☹️ im searching this username and i want it can u please give me bcoz
im planning something big so peoples get easier to find me.

**Comment by divine** [comment]
No, just no.
